name: First Workflow
on:
  push: 
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: print a welcome message
        run: echo "hi"

      - name: checkout repository
        uses: actions/checkout@v7.0.0

      - name: list repoistory files
        run: ls -la

      
